{%- set name = "diffpy.utils" -%}
{%- set version = "3.4.0" -%}
{%- set sha256 = "24e4c6108e87345be3518e085b2ebc85efb3e4fc7ff1097297cdcf92e7d9a9b9" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_utils/diffpy_utils-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  preserve_egg_dir: true
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - setuptools
    - numpy >=1.3

test:
  imports:
    - diffpy
    - diffpy.utils
    - diffpy.utils.parsers
    - diffpy.utils.tests

  requires:
    - pip
    - pytest
    - pytest-mock
    - freezegun

  commands:
    - pip check
    - python -m pytest

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The diffpy.utils package provides functions for extracting array data from variously formatted text files and wx GUI utilities used by the PDFgui program. The package also includes an interpolation function based on the Whittaker-Shannon formula that can be used to resample a PDF or other profile function over a new grid.
  doc_url: http://diffpy.github.io/diffpy.utils/
  dev_url: https://github.com/diffpy/diffpy.utils/

extra:
  recipe-maintainers:
    - sbillinge
    - Sparks29032
    - dragonyanglong
    - CJ-Wright
    - pavoljuhas
