{%- set name = "diffpy.utils" -%}
{%- set version = “3.4.1" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_utils/diffpy_utils-{{ version }}.tar.gz
  sha256: 2b5a6a35f0bfb5099d9dabcd64255b806d73854d065562f275ea34fbef74e82b

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - setuptools
    - numpy >=1.3

test: 
  requires:
    - pip
    - pytest
    - pytest-mock
    - freezegun
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The diffpy.utils package provides functions for extracting array data from variously formatted text files and wx GUI utilities used by the PDFgui program. The package also includes an interpolation function based on the Whittaker-Shannon formula that can be used to resample a PDF or other profile function over a new grid.
  doc_url: http://diffpy.github.io/diffpy.utils/
  dev_url: https://github.com/diffpy/diffpy.utils/

extra:
  recipe-maintainers:
    - bobleesj
    - sbillinge
    - Sparks29032
    - dragonyanglong
    - CJ-Wright
    - pavoljuhas
