{% set name = "diffpy.utils" %}
{% set version = "3.2.4" %}
{% set sha256 = "05b62506ac8f3448b2eceb54ad3de36218b4525fe41a8438137561d6384dd1b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  preserve_egg_dir: true
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip

  run:
    - python >=3.7
    - setuptools
    - numpy >=1.3

test:
  imports:
    - diffpy
    - diffpy.utils
    - diffpy.utils.parsers
    - diffpy.utils.tests

  requires:
    - pytest

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The diffpy.utils package provides functions for extracting array
    data from variously formatted text files and wx GUI utilities used by the
    PDFgui program. The package also includes an interpolation function based on
    the Whittaker-Shannon formula that can be used to resample a PDF or other
    profile function over a new grid.
  doc_url: http://www.diffpy.org/diffpy.utils/
  dev_url: https://github.com/diffpy/diffpy.utils

extra:
  recipe-maintainers:
    - sbillinge
    - Sparks29032
    - dragonyanglong
    - CJ-Wright
    - pavoljuhas
