{% set name = "diffpy.utils" %}
{% set version = "3.7.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_utils/diffpy_utils-{{ version }}.tar.gz
  sha256: cc50e78883f66258cf75a1a5342746789d5d1ef8044991305023189f6bf2088f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - xraydb
    - scipy

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-mock
    - freezegun
    - DeepDiff
  source_files:
    - tests

  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.utils/
  summary: Shared utilities for diffpy packages.
  license: LicenseRef-diffpy
  license_file: LICENSE.rst
  description: |
    The diffpy.utils package provides functions for extracting array data from variously formatted text files and wx GUI utilities used by the PDFgui program. The package also includes an interpolation function based on the Whittaker-Shannon formula that can be used to resample a PDF or other profile function over a new grid.
  doc_url: http://diffpy.github.io/diffpy.utils/
  dev_url: https://github.com/diffpy/diffpy.utils/

extra:
  recipe-maintainers:
    - yucongalicechen
    - bobleesj
    - sbillinge
    - Sparks29032
    - cadenmyers13
    - dragonyanglong
    - CJ-Wright
    - pavoljuhas
